# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Pu/cfpMNw1b9um+540qoh7u1PQGfIsuW+PGEo+AnwbqsQqDM0MygRb4tK4aKKbZdK8O+DdauPPdNBieDtSOT7MarjBMQzpXgwSXQNkBb6YBwCfl/MRzYFZRQkxUDU0RwJdYBATBo95dYF07jJaREnKFfH4bP7AZGSvCtSfCzZaxUjluG7bpII/5WMk7z42MLLE/7RuJ9sM1OwNiPLTgWFkDoonQO8gMdQ8q6b9csvEr3bHOUrL90QmFNf47Kree35rSBX1t3r/H5eBfs+NHY6AUAcLSAOxqxwTbbn5p9TcMFRrn4MK9ZoFNzOjYZkN3xOYizUWTgrH9Xh+ke23ZNVLm4rRfY0f0kwHrsYDsanWAhIcoMJMUmCsHLrFwWxrn/p0HyHfzp415WFtRUIg9csEp5OzUG1D7WLk/IReRjrOqZ/VKd3Lju8xywMex9h1vnJcI5yLN5Q3EWL0acNZ9KEWVvwOi33CXQOYK23WHWXjSJ8elZi+Fi8nMcbvMRLNHBfGnSwbwVcQ2GV93HNjFig9QN09JiDbzPKHdhPjQ0hTuTlCTPgl5n2eUdC0ykJ7YdeYVnNA8d/EsZWnhmFFyDT3niihVyrTTwkK1wNyL4GlNQDekqp7a0sN6Ui8Qo8Tzr6NyICTr0EoyKKsylayMme0EqYt9IpD0LDJXmh4qCOAo="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
