travis:
  secure:
    BINSTAR_TOKEN: Co2eXjbjfFTqRULf58u/EKokgvb6unT9x+Dt2RZFdN/99iwahFnjeq57AJXoDhuy6AV0T5zHLnvmptFnXWnHiR+Rc3MWetKj63jv96yb3IpyvB0U9nl8aNfXIvoDv33O2x1c+eocGxsPgQyMDzQrYVxy3un0iD7aTUg9oP050LYFmiHdkW0XeHHmbA5LACNuJO2Nh5tqBAyHGoom9K9BnVC1qxTd2ozlu4PTBnyNAsvud6Db9NEHNqtJca1D/TazIaMTt8L11DOv0EEXHvVUgTTCHInbanVeVa9PNnSvC+rt7mbIPB4K25IUgJzn7xsN5oWRm8OFd+efFOPBNZvmNhWWn/2LQCeChLo0di5X0kxtWq7Jsl3h78mE4Ea/uoSNstYJ/soF7tQxweXuqL67At8oNdLpV//YXZD3mzPfCY2IiToSffervUrBxkdUd9MJNgI36VEetAPZVt04/mZlGpVUccYYqfj/AP08LJJN8GaW85SP1hqsi6V36VfudIxahVOIRci/tZFZrz5mvJlg3/z6w13XtgkT2YHV0r82xNTIQPuxvLPdzIwH/f2vhvznt79/U5lW/6OX6mgJfY/PWRTqhw3yggciL4GsCjb5AxqDbi9BTGqVLGZBICqnJ74aEGgCp7AflHhk56lWBLux4hEJdkqHbT9LKY18JY2R5eI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
